# Physical road infrastructure

## Dedicated lanes for connected and automated vehicles (CAV)

### Synonyms
*AV-dedicated lanes*, *dedicated corridors*

### Definition
Dedicated lane for connected and autonomous vehicles features additional infrastructure or sensors to increase the reliability of Advanced Driver Assistant Systems (ADAS). Only automated driving vehicles are allowed to drive on these lanes. The typical applications include cooperative and adaptive cruise control based on sensors with the infrastructure, lane keeping, fuel use optimization and road pricing possibilities (Broek et al., 2011). The introduction of dedicated lanes for CAV is expected to have direct consequences on the traffic flow on the highways and a nearby road network. In particular, a study conducted in Singapore showed that dedicated lanes on the highways can reduce travel time of CAVs by approximately 25% (if the saturation on the lane is not reached) at the cost of a delay for conventional cars of approximately 7%, due to the reduced capacity (Ivanchev et al., 2017). They were also demonstrated to have a positive effect on fuel consumption. <br/><br/>
Moreover, the throughput, defined as a number of vehicles passing through the road in a given time interval, increased as a result of introduction of dedicated lanes for AVs (Kumar et al., 2020). This effect, however, was associated with a decrease in throughput of smaller roads due to the preference of AVs for highways because of time savings, which in turn can result in time loss for conventional cars. What is more, the benefits from increased capacity of AV-only lanes can be further amplified through setting a higher speed limits for these lanes (Ye & Yamamoto, 2018). With respect to the demand for different road types the study found that the introduction of dedicated CAV lanes will increase the demand of conventional cars for major road (but smaller than highways) and minor roads as a substitution for more congested highways due to the dedicated AV lanes. <br/><br/>
In contrast, study by Chen et al. (2016) showed that the implementation of CAV dedicated lanes has a potential of maximizing traffic capacity on these lanes in a mix-traffic context while having effectively no impact on conventional traffic capacity. Further, in order to use efficiently CAV dedicated lanes, which may be underutilized at the early stage, it is proposed to allow conventional cars to enter the AVs-only lanes after toll payment. This solution stems from currently operational across the world High Occupancy Vehicle (HOV) lanes. This joint approach is claimed to improve the throughput of individual road as well as enhance system-wide flow distribution within the network (Liu & Song, 2019).

### Key stakeholders

- **Affected**: Conventional Cars’ Drivers, Car Manufacturers, Insurers
- **Responsible**: Road Infrastructure Agencies, Local and National Governments

### Current state of art in research
Current research focuses on gathering the evidence of the impact of the introduction of dedicated lanes on traffic flow, driver behavior adoption, safety and efficiency. Furthermore, it analyses the factors which influence them, by testing different design and operation configurations, road types and utilization policies (Rad et al., 2020). Both, field operational testing and driving simulator studies have been conducted to investigate the influence of different designs of dedicated lanes on drivers in conventional cars and those featuring some degree of automation (Guin et al., 2008, Zhong, 2018). In particular, a number of studies compared distinct access types of dedicated lanes (Zhong, 2018, Yang et al., 2019). They showed that dedicated lanes with limited access performed better in terms of travel time and throughput compared to dedicated lanes with continuous access. Moreover, the probability of vehicles platooning was significantly higher on dedicated lanes with limited access. On the other hand, it was showed that collision rates near the entry or exit of these limited access lanes are higher (Rad et al. 2020).

### Current state of art in practice
Currently state of Michigan together with several private partners including Ford and Alphabet Inc. are planning to dedicate 65 km of a highway between Detroit and Ann Arbor for the sole movement of autonomous vehicles including buses and shuttles (Krisher & Eggert, 2020). Similar initiatives are taking place in other countries, for instance, China set out to build nearly 100 km of 8-lane highway linking Beijing and the Xiongan New Area, from which 2 lanes will be allocated for the automated traffic. The completion of the construction phase is predicted by the end of 2020, while its opening is for traffic is expected in June 2021 (Syncedreview.com, 2020). In Europe, there is on-going SHOW (SHared automation Operating models for Worldwide adoption) project which aims to deploy about seventy automated vehicles in 21 European cities. To assess how they can best be integrated vehicles will be used in different settings in mixed traffic and dedicated lanes. However, for safety reasons the driver will be on-board (CORDIS, 2020). 

### Relevant initiatives in Austria

- https://www.tugraz.at/fileadmin/user_upload/Institute/IHF/Projekte/ENABLE-S3_SummaryofResults_May2019.pdf 
- https://www.ait.ac.at/themen/verkehrssicherheit-und-unfallforschung/projects/via-autonom/ 

### Impacts with respect to Sustainable Development Goals (SDGs)

```{r table1, echo=FALSE, results='asis'}
cat('| Impact level| Indicator|Impact direction| Goal description and number|Source|
|:------------:|:-----------:|:------------:|:------------:|:------------:|
|Individual|Fuel consumption reduced|+|Environmental sustainability (*7,12-13,15*)|Ivanchev et al., 2017|
|Individual|Travel time reduced|          +|Sustainable economic development (*8,11*)|Zhong, 2018;Yang et al., 2019|
|          Systemic|         Collision rate reduced|          +|Health & Wellbeing (*3*)|Zhang et al., 2020|
|          Systemic|         Emissions rate reduced|          +|Environmental sustainability (*7,12-13,15*)|Al Alam at al., 2010|
|          Systemic|         Congestion|          ~|Sustainable economic development (*8,11*)|Ivanchev et al., 2017;Kumar et al., 2020|
|          Systemic|         Novel designs tested|          +|Innovation & Infrastructure (*9*)|Guin et al., 2008;Zhong, 2018;Krisher & Eggert, 2020|
|          Systemic|       SHOW EU initiative  |          +|Partnership & collaborations (*17*)|CORDIS, 2020|')
```

### Technology readiness level
5-6

### Societal readiness level
TBD

### Open questions

1. What are the potential benefits of dedicated AV lanes when coupled with smart platooning strategies?
2. How and to what degree will joint concepts by automotive sector, fleet and road
operators will improve traffic management establishing dynamic traffic regulations even across
borders?
3. What are the roles and responsibilities of the different stakeholders of physical infrastructure for connected and automated vehicles? 
4. Should the vehicle cope with any road infrastructure, and if not, what demands can be set to adapt the existing infrastructure? 
5. How to ensure continuity between those different environments?
6. Which tools (e.g. micro- and macroscopic transport modelling, impact assessment) can enable
cities to assess the impact of automated vehicles on their physical road infrastructure and
balance the needs of automated vehicles against the needs of existing modes (conventional
vehicles, public transport, pedestrians and cyclists). (ERTRAC, 2019)

### Further links

-	https://knowledge-base.connectedautomateddriving.eu/wp-content/uploads/2019/12/SMART_2010-0064-study-report-final_V1-2.pdf 
-	https://show-project.eu/ 

### References

- Al Alam, A., Gattami, A., & Johansson, K. H. (2010, September). An experimental study on the fuel reduction potential of heavy duty vehicle platooning. In 13th International IEEE Conference on Intelligent Transportation Systems (pp. 306-311). IEEE.
Broek, S. M., van Nunen, E., & Zwijnenberg, H. (2011). Definition of necessary vehicle and infrastructure systems for automated driving. Retrieved January, 3, 2017.
- Chen, Z., He, F., Zhang, L., & Yin, Y. (2016). Optimal deployment of autonomous vehicle lanes with endogenous market penetration. Transportation Research Part C: Emerging Technologies, 72, 143-156.
- CORDIS | European Commission. (20 Apr 2020). Retrieved 13 November 2020, from https://cordis.europa.eu/project/id/875530
- ERTRAC Working Group. (2019). Connected Automated Driving Roadmap. version, 8, 2019-08.
- Guin, A., Hunter, M., & Guensler, R. (2008). Analysis of reduction in effective capacities of high-occupancy vehicle lanes related to traffic behavior. Transportation Research Record, 2065(1), 47-53.
- Ivanchev, J., Knoll, A., Zehe, D., Nair, S., & Eckhoff, D. (2017). Potentials and implications of dedicated highway lanes for autonomous vehicles. arXiv preprint arXiv:1709.07658.
- Krisher, T., & Eggert, D. (14 Aug 2020). Michigan plans dedicated road lanes for autonomous vehicles. Retrieved 12 November 2020, from https://abcnews.go.com/Technology/wireStory/michigan-plans-dedicated-road-lanes-autonomous-vehicles-72352758
- Kumar, A., Guhathakurta, S., & Venkatachalam, S. (2020). When and where should there be dedicated lanes under mixed traffic of automated and human-driven vehicles for system-level benefits?. Research in Transportation Business & Management, 100527.
- Liu, Z., & Song, Z. (2019). Strategic planning of dedicated autonomous vehicle lanes and autonomous vehicle/toll lanes in transportation networks. Transportation Research Part C: Emerging Technologies, 106, 381-403.
- Rad, S. R., Farah, H., Taale, H., van Arem, B., & Hoogendoorn, S. P. (2020). Design and operation of dedicated lanes for connected and automated vehicles on motorways: A conceptual framework and research agenda. Transportation Research Part C: Emerging Technologies, 117, 102664.
- Syncedreview.com (31 Aug 2020). Beijing Builds 100km Highway Lanes for Self-Driving Cars with Unmanned Machineries. Retrieved 12 November 2020, from https://syncedreview.com/2020/08/31/beijing-builds-100km-highway-lanes-for-self-driving-cars-with-unmanned-machineries/
- Yang, D., Farah, H., Schoenmakers, M. J., & Alkim, T. (2019). Human drivers behavioural adaptation when driving next to a platoon of automated vehicles on a dedicated lane and implications on traffic flow: a driving simulator and microscopic simulation study in the Netherlands. In 98th Annual Meeting of the Transportation Research Board (pp. 19-00582).
- Ye, L., & Yamamoto, T. (2018). Impact of dedicated lanes for connected and autonomous vehicle on traffic flow throughput. Physica A: Statistical Mechanics and its Applications, 512, 588-597.
- Zhang, J., Wu, K., Cheng, M., Yang, M., Cheng, Y., & Li, S. (2020). Safety Evaluation for Connected and Autonomous Vehicles’ Exclusive Lanes considering Penetrate Ratios and Impact of Trucks Using Surrogate Safety Measures. Journal of advanced transportation, 2020. 
- Zhong, Z. (2018). Assessing the effectiveness of managed lane strategies for the rapid deployment of cooperative adaptive cruise control technology.


